movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
        # path('', views.index),
        path('', views.index, name="index"),
        path('<int:movie_pk>/', views.detail, name="detail"),
        path('<int:movie_pk>/delete/', views.delete, name="delete"),
        path('<int:movie_pk>/scores/new/', views.scnew, name="scnew"),
        path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.scdel, name="scdel"),
        path('<int:movie_pk>/edit/', views.edit, name="edit"),
        path('<int:pk>/update/', views.update),
    ]

project07/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    # genre = models.CharField(max_length=20)
    # score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete = models.CASCADE)

class Score(models.Model):
    content = models.TextField()
    score = models.FloatField()
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Score, Genre
from django.db.models import Avg

# Create your views here.
def index(request):
    # a = Movie.objects.filter(title='title')
    # movies = Movie.objects.all()
    movies = Movie.objects.annotate(score_avg=Avg('score__score')).all()
    # print(movies_genre)
    return render(request, 'index.html',{'movies': movies})

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    scores = movie.score_set.all
    context = {
        'movie':movie,
        'scores':scores
    }
    return render(request, 'detail.html', context)
    
def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.delete()
    return redirect('movies:index')

def scnew(request, movie_pk):
    if request.method == "POST":
        movie = Movie.objects.get(pk=movie_pk)
        score = Score()
        score.content = request.POST.get('content')
        score.score =  request.POST.get('score')
        score.movie = movie
        # score = Score(content=content, score=score)
        score.save()
    return redirect('movies:detail', movie_pk)
    
def scdel(request, movie_pk, score_pk):
    if request.method == "POST":
        score = Score.objects.get(pk=score_pk)
        score.delete()
    return redirect('movies:detail', movie_pk)
    # movie.pk 가 아닌 movie_pk 를 넘겨줘야함.
    
    
    
def edit(request, movie_pk):
    if request.method == 'POST':
        genre_id = request.POST.get('genre')
        genre = Genre.objects.get(pk = genre_id)
        movie = Movie.objects.get(pk=movie_pk)
        movie.genre = genre
        movie.title = request.POST.get('title')
        movie.description = request.POST.get('description')
        movie.audience = request.POST.get('audience')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        movie = Movie.objects.get(pk=movie_pk)
        genres = Genre.objects.all()
        context = {
            'movie':movie,
            'genres':genres
            }
        return render(request, 'edit.html', context)
    
def update(request, pk):
    u_movie = Movie.objects.get(pk=pk)
    u_movie.title = request.POST.get('title')
    u_movie.audience = request.POST.get('audience')
    u_movie.genre = request.POST.get('genre')
    u_movie.score = request.POST.get('score')
    u_movie.poster_url = request.POST.get('poster_url')
    u_movie.description = request.POST.get('description')
    # u_movie = Movie(title=title, audience=audience, genre=genre, score=score, poster_url=poster_url, description=description)
    u_movie.save()
    return redirect('/movies/')

movies/templates/detail.html
<h1>{{movie.title}}</h1>
<p>누적관객수:{{movie.audience}}</p>
<p>장르:{{ movie.genre.name }}</p>
<p>설명: {{ movie.description }}</p>

<img src = "{{movie.poster_url}}" alt = "포스터">
<hr>
<p>영화 평가하기 (총 {{ scores.count }}개의 글이 달림)</p>

<form action = "{% url 'movies:scnew' movie.pk %}" method="POST">
    {% csrf_token %}
    코멘트 : <input type ="text" name ="content"> <br>
    
    평점 : <input type ="float" name ="score"> 
    <input type = "submit">
</form>

{% for score in scores %}
평점: {{score.score}}, 코멘트: {{ score.content }}
    <form action="{% url 'movies:scdel' movie.pk score.pk %}" method="POST" style ="display: inline" onsubmit="return confirm('삭제하시겠습니까?')">
        {% csrf_token %}
        <input type = "submit" value="삭제">
    </form>
    <br>
{% empty %}
    <b><p>댓글이 없어요 ' <'</p></b>    
{% endfor %}
<hr>
<a href='{% url "movies:index" %}'>목록</a>&nbsp;&nbsp;<a href='{% url "movies:delete" movie.id %}'>삭제</a>&nbsp;<a href='{% url "movies:edit" movie.pk %}'>수정</a>

movies/templates/edit.html
<form method="POST">
    {% csrf_token %}
    영화제목:<input type="text" name="title" value="{{movie.title}}"><br>
    관객 수:<input type="int" name="audience" value="{{movie.audience}}"><br>
    설명:<input type="text" name="description" value = "{{movie.description}}"><br>
    영화 소개:<textarea name="description">{{movie.description}}</textarea><br>
    장르 : <select name="genre">
        {% for genre in genres %}
            {% if genre.id == movie.genre.id %}
                <option value="{{genre.id}}"selected>{{genre.name}}</option>
            {% else %}
                <option value="{{genre.id}}">{{genre.name}}</option>
            {% endif %}
        {% endfor %}
    </select>
    <!--평점:<input type="int" name="score" value=""><br>-->
    <!--포스터:<input type="text" name="poster_url" value="{{movie.poster_url}}"><br>-->
    
    <input type="submit">
</form>

movies/templates/index.html
<h1>영화 목록</h1>
<br>
{% for movie in movies %}
<a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a> <br>
<img src="{{ movie.poster_url }}" alt = '포스터'>
<p> 평점: {{ movie.score_avg }} </p><hr>
{% endfor %}

movies/templates/scnew.html
<form method="POST">
    {% csrf_token %}
    코멘트 : <input type ="text" name ="content"> <br>
    
    평점 : <input type ="float" name ="score"> 
    <input type = "submit">    
</form>